#!/usr/bin/env perl

# command:
#   $ track 30 "I did stuff"
#   $ track 1h "I did twice as much stuff"
#
# format:
#   - First arg is how much time spent
#   - Second arg is a description

# place where data is stored
$datadir = "~/Documents/Tracker/";
`mkdir -p $datadir`;

# get today's date, formatted
($day, $month, $year) = (localtime)[3,4,5];
$fdate = sprintf("%04d-%02d-%02d", $year + 1900, $month + 1, $day);

# set the output file name
$filename = $datadir.$fdate."-time-log.txt";

# expand the ~ to user's home dir: http://docstore.mik.ua/orelly/perl/cookbook/ch07_04.htm
$filename =~ s{ ^ ~ ( [^/]* ) } { $1 ? (getpwnam($1))[7] : ( $ENV{HOME} || $ENV{LOGDIR} || (getpwuid($>))[7] ) }ex;


if ($ARGV[0] eq "-r") {
    if (-e $filename) {
        open REPORTFILE, "< $filename" or die "Couldn't open $filename: $!";
        print "# Today's report\n";
    }
    else {
        print STDERR "No time log for today. Track some time first.\n";
    }
}
else {
    # open the output file
    if (!-e $filename) {
        open TIMELOG, ">> $filename" or die "Couldn't open $filename: $!";
        print TIMELOG "$fdate\n";
    }
    else {
        open TIMELOG, ">> $filename" or die "Couldn't open $filename: $!";
    }
    
    # process arguments
    ($minutes, $message) = (@ARGV)[0,1];
    print TIMELOG "$minutes: $message\n";
}
